import test from 'node:test';
import assert from 'node:assert/strict';
import {SyncAudio} from '../public/audio.js';
// Exercise public audio controls against a deterministic audio-device seam.
class Param {value=1;cancelScheduledValues(){}setTargetAtTime(v){this.value=v}}
class Node {connect(){return this}disconnect(){}}
class Source extends Node {started=false;stopped=false;start(){this.started=true}stop(){this.stopped=true;this.onended?.()}}
class Context {state='suspended';currentTime=0;destination={};sources=[];createGain(){const n=new Node();n.gain=new Param();return n}createAnalyser(){const n=new Node();n.getFloatTimeDomainData=a=>a.fill(.05);return n}createDynamicsCompressor(){const n=new Node();for(const k of ['threshold','knee','ratio','attack','release'])n[k]=new Param();return n}createBufferSource(){const n=new Source();this.sources.push(n);return n}async resume(){this.state='running'}async suspend(){this.state='suspended'}async decodeAudioData(){return {duration:.5}}}
globalThis.window={AudioContext:Context};globalThis.document={hidden:false};globalThis.localStorage={getItem(){return null},setItem(){}};
const okFetch=async()=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(2)});
test('no context or playback without explicit enable',()=>{const a=new SyncAudio();assert.equal(a.context,null);assert.equal(a.enabled,false);assert.equal(a.play('win'),false)});
test('music loop is single; mute stops every source; gains are independent',async()=>{globalThis.fetch=okFetch;const a=new SyncAudio();await a.setEnabled(true);const loop=a.music;a.startMusic();a.startMusic();assert.equal(a.music,loop);assert.equal(a.context.sources.filter(s=>s.loop).length,1);a.setVolume('music',0);assert.equal(a.musicGain.gain.value,0);assert.equal(a.fxGain.gain.value,.55);a.play('win');await a.setEnabled(false);assert.equal(a.effects.size,0);assert.equal(a.music,null);assert.equal(a.context.state,'suspended');assert.ok(a.context.sources.every(s=>s.stopped));assert.equal(a.play('reveal'),false)});
test('mute during loading prevents late playback',async()=>{let release;const pending=new Promise(r=>release=r);globalThis.fetch=async()=>{await pending;return okFetch()};const a=new SyncAudio();const enabling=a.setEnabled(true);await Promise.resolve();await a.setEnabled(false);release();await enabling;assert.equal(a.enabled,false);assert.equal(a.music,null);assert.equal(a.context.sources.length,0)});
test('on-off-on during loading ends with exactly one active loop',async()=>{let release;const pending=new Promise(r=>release=r);globalThis.fetch=async()=>{await pending;return okFetch()};const a=new SyncAudio();const first=a.setEnabled(true);await Promise.resolve();await a.setEnabled(false);const second=a.setEnabled(true);release();await Promise.all([first,second]);assert.equal(a.enabled,true);assert.equal(a.context.sources.filter(s=>s.loop&&!s.stopped).length,1);await a.setEnabled(false)});
test('failed sound fetch disables sound and allows a clean retry',async()=>{globalThis.fetch=async()=>({ok:false});const a=new SyncAudio();await a.setEnabled(true);assert.equal(a.enabled,false);assert.match(a.error,/could not load/);globalThis.fetch=okFetch;await a.setEnabled(true);assert.equal(a.enabled,true);assert.equal(a.error,'');await a.setEnabled(false)});
test('background mutes effects; muted audio never resumes on return',async()=>{globalThis.fetch=okFetch;const a=new SyncAudio();await a.setEnabled(true);a.play('win');document.hidden=true;await a.visibility(true);assert.equal(a.context.state,'suspended');assert.equal(a.effects.size,0);assert.equal(a.play('tick-1'),false);await a.setEnabled(false);document.hidden=false;await a.visibility(false);assert.equal(a.context.state,'suspended');assert.equal(a.music,null)});
test('live runtime handoff mutes parent audio',async()=>{globalThis.fetch=okFetch;const a=new SyncAudio();await a.setEnabled(true);a.setPhase('live');assert.equal(a.enabled,false);assert.equal(a.music,null);assert.equal(a.effects.size,0)});
test('rapid cues are bounded and same-cue spam is rejected',async()=>{globalThis.fetch=okFetch;const a=new SyncAudio();await a.setEnabled(true);for(const name of ['round','lock','reveal','win','tick-1','tick-2'])a.play(name);assert.ok(a.effects.size<=4);assert.equal(a.play('tick-2'),false);await a.setEnabled(false)});
